# Generated by Django 4.1.4 on 2023-01-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('AssetId', models.AutoField(primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('FileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('CategoryDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('UserAssetsId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=100)),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assets')),
            ],
        ),
    ]
