# Generated by Django 4.0.1 on 2022-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='Category',
            field=models.CharField(max_length=100),
        ),
    ]
